name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        working-directory: ./Client
        run: npm install
        
      - name: Install pkg
        run: npm install -g pkg

      - name: Build for Windows
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: p2p-file-transfer-win
          path: p2p-file-transfer-win.exe
